<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;900&display=swap" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Malgun+Gothic:wght@400&display=swap" />
	<link rel="stylesheet" href="<c:url value='/css/study_details.css'/>" />
  </head>
  <body>
    <div class="main-container">
      <div class="study-detail">
        <jsp:include page="../navigation/navigation.jsp" />
        
        <div class="flex-row-d">
          <span class="study-detail-view">스터디 상세보기</span
          ><span class="toeic-study">단기간 토익 점수 상승을 위한 스터디</span>
        </div>
        <div class="flex-row">
          <button class="frame"><span class="number-3">3</span></button>
          <div class="rectangle-2">
            <div class="flex-column-f">
              <span class="notice">공지사항</span
              ><span class="important-notice"
                >아주아주아주아주아주아주 중요한 공지</span
              ><span class="important-notice-3"
                >아주아주아주아주아주아주 중요한 공지</span
              >
            </div>
            <div class="flex-column">
              <div class="notification-outlined">
                <div class="vector-4"></div>
              </div>
              <div class="dot"><div class="vector-5"></div></div>
              <div class="dot-6"><div class="vector-7"></div></div>
            </div>
          </div>
          <span class="more">더보기</span><span class="time-ago">3시간 전</span
          ><span class="time-ago-8">3시간 전</span>
        </div>
        <div class="flex-row-e">
          <div class="frame-9"><span class="number-4">4</span></div>
          <div class="rectangle-a">
            <div class="flex-column-ee">
              <span class="assignment">과제</span
              ><span class="essential-grammar">토익 필수 영문법 23~36p</span
              ><span class="essential-vocabulary"
                >토익 필수 영단어 Day7~9 암기</span
              ><span class="mock-test-notes">제 n회 모의고사 오답노트</span>
            </div>
            <div class="flex-column-dde">
              <div class="book"><div class="vector-b"></div></div>
              <div class="dot-c"><div class="vector-d"></div></div>
              <div class="dot-e"><div class="vector-f"></div></div>
              <div class="dot-10"><div class="vector-11"></div></div>
            </div>
          </div>
          <span class="more-12">더보기</span><span class="d-day">D-Day</span
          ><span class="d-day-13">D-Day</span><span class="d-3">D-3</span>
        </div>
        <div class="flex-row-14">
          <button class="frame-15"><span class="span-1">1</span></button
          ><span class="span-il">일</span><span class="span-mon">월</span
          ><span class="span-tue">화</span><span class="span-wed">수</span
          ><span class="span-thu">목</span><span class="span-fri">금</span
          ><span class="span-sat">토</span>
          <div class="rectangle-16"></div>
          <span class="span-31">31</span><span class="span-1-17">1</span
          ><span class="span-2">2</span><span class="span-3">3</span
          ><span class="span-4">4</span><span class="span-5">5</span
          ><span class="span-6">6</span>
          <div class="calendar-table">
            <div class="table">
              <div class="row">
                <div class="cell">
                  <div class="content"><span class="text"></span></div>
                </div>
                <div class="cell-18">
                  <div class="content-19"><span class="text-1a"></span></div>
                </div>
                <div class="cell-1b">
                  <div class="content-1c"><span class="text-1d"></span></div>
                </div>
                <div class="cell-1e">
                  <div class="content-1f"><span class="text-20"></span></div>
                </div>
                <div class="cell-21">
                  <div class="content-22"><span class="text-23"></span></div>
                </div>
                <div class="cell-24">
                  <div class="content-25"><span class="text-26"></span></div>
                </div>
                <div class="cell-27">
                  <div class="content-28"><span class="text-29"></span></div>
                </div>
              </div>
              <div class="row-2a">
                <div class="cell-2b">
                  <div class="content-2c"><span class="text-2d"></span></div>
                </div>
                <div class="cell-2e">
                  <div class="content-2f"><span class="text-30"></span></div>
                </div>
                <div class="cell-31">
                  <div class="content-32"><span class="text-33"></span></div>
                </div>
                <div class="cell-34">
                  <div class="content-35"><span class="text-36"></span></div>
                </div>
                <div class="cell-37">
                  <div class="content-38"><span class="text-39"></span></div>
                </div>
                <div class="cell-3a">
                  <div class="content-3b"><span class="text-3c"></span></div>
                </div>
                <div class="cell-3d">
                  <div class="content-3e"><span class="text-3f"></span></div>
                </div>
              </div>
              <div class="row-40">
                <div class="cell-41">
                  <div class="content-42"><span class="text-43"></span></div>
                </div>
                <div class="cell-44">
                  <div class="content-45"><span class="text-46"></span></div>
                </div>
                <div class="cell-47">
                  <div class="content-48"><span class="text-49"></span></div>
                </div>
                <div class="cell-4a">
                  <div class="content-4b"><span class="text-4c"></span></div>
                </div>
                <div class="cell-4d">
                  <div class="content-4e"><span class="text-4f"></span></div>
                </div>
                <div class="cell-50">
                  <div class="content-51"><span class="text-52"></span></div>
                </div>
                <div class="cell-53">
                  <div class="content-54"><span class="text-55"></span></div>
                </div>
              </div>
              <div class="row-56">
                <div class="cell-57">
                  <div class="content-58"><span class="text-59"></span></div>
                </div>
                <div class="cell-5a">
                  <div class="content-5b"><span class="text-5c"></span></div>
                </div>
                <div class="cell-5d">
                  <div class="content-5e"><span class="text-5f"></span></div>
                </div>
                <div class="cell-60">
                  <div class="content-61"><span class="text-62"></span></div>
                </div>
                <div class="cell-63">
                  <div class="content-64"><span class="text-65"></span></div>
                </div>
                <div class="cell-66"><div class="content-67"></div></div>
                <div class="cell-68">
                  <div class="content-69"><span class="text-6a"></span></div>
                </div>
              </div>
              <div class="row-6b">
                <div class="cell-6c">
                  <div class="content-6d"><span class="text-6e"></span></div>
                </div>
                <div class="cell-6f">
                  <div class="content-70"><span class="text-71"></span></div>
                </div>
                <div class="cell-72">
                  <div class="content-73"><span class="text-74"></span></div>
                </div>
                <div class="cell-75">
                  <div class="content-76"><span class="text-77"></span></div>
                </div>
                <div class="cell-78">
                  <div class="content-79"><span class="text-7a"></span></div>
                </div>
                <div class="cell-7b">
                  <div class="content-7c"><span class="text-7d"></span></div>
                </div>
                <div class="cell-7e">
                  <div class="content-7f"><span class="text-80"></span></div>
                </div>
              </div>
            </div>
          </div>
          <span class="number-7">7</span><span class="number-8">8</span
          ><span class="number-9">9</span><span class="number-10">10</span
          ><span class="number-11">11</span><span class="number-12">12</span
          ><span class="number-13">13</span><span class="room-301">301호</span>
          <div class="blackboard"><div class="vector-81"></div></div>
          <span class="number-19">19</span><span class="number-14">14</span
          ><span class="number-15">15</span><span class="number-16">16</span
          ><span class="number-17">17</span><span class="number-18">18</span
          ><span class="number-20">20</span
          ><span class="wednesday-6-30">수요일 6시 반</span>
          <div class="clock">
            <div class="blackboard-82"></div>
            <div class="group-83"></div>
          </div>
          <span class="number-21">21</span><span class="number-22">22</span
          ><span class="span-23">23</span><span class="span-24">24</span
          ><span class="span-25">25</span><span class="span-26">26</span
          ><span class="span-27">27</span>
          <div class="div-rectangle">
            <div class="div-flex-row-df">
              <div class="div-vector"></div>
              <span class="text-61">팀원들 (6/10)</span>
            </div>
            <div class="div-flex-row-f">
              <div class="div-mdi-crown"><div class="div-vector-84"></div></div>
              <span class="text-62">조은향 </span>
            </div>
            <span class="text-63">김희선</span
            ><span class="text-64">손다현</span
            ><span class="text-65">김지은</span
            ><span class="text-66">김솜솜</span
            ><span class="text-67">양갱이</span>
          </div>
          <span class="span-28">28</span><span class="span-29">29</span
          ><span class="span-30">30</span><span class="span-31-85">31</span
          ><span class="span-1-86">1</span><span class="span-2-87">2</span>
        </div>
        <div class="div-rectangle-88">
          <div class="div-flex-row">
            <span class="text-6e">공지 사항</span
            ><span class="text-6f">일정 </span><span class="text-70">과제</span>
          </div>
          <div class="div-flex-row-a">
            <span class="text-71">비상비상 발등튀김 구출작전</span>
            <div class="div-regroup">
              <span class="text-72">토익 필수 영문법 23~36p</span
              ><span class="text-73">아주 중요한 공지</span>
            </div>
          </div>
          <div class="div-flex-row-89">
            <span class="text-74">토익 필수 영단어 Day7~9 암기</span>
            <div class="div-rectangle-8a">
              <div class="div-rectangle-8b">
                <div class="div-vector-8c"></div>
              </div>
            </div>
            <div class="div-rectangle-8d">
              <div class="div-vector-8e"></div>
            </div>
          </div>
          <div class="div-flex-row-a-8f">
            <button class="button-frame">
              <span class="span-2-90">2</span>
            </button>
            <div class="div-rectangle-91">
              <div class="div-basil-plus-solid">
                <div class="div-vector-92"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="div-rectangle-93"></div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
